import createClient, {type Middleware} from "openapi-fetch";
import {promiseTimeout} from "@/lib/utils";
import type {paths} from "@/types/api-schema"; // generated by openapi-typescript

export const fetchClient = createClient<paths>({
	baseUrl: import.meta.env.VITE_SERVER_URL,
	credentials: "include",
});

if (import.meta.env.DEV) {
	const delayMiddleware: Middleware = {
		async onRequest({request}) {
			await promiseTimeout(500);
			return request;
		},
	};

	fetchClient.use(delayMiddleware);
}
